version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_pass
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend
    #restart: always #startet neu nach fehler
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - "./backend/.env"
    volumes:
      - ./backend:/usr/src/app

volumes:
  mongo_data:
