POST http://localhost:5000/api/spots/680a0ea0fdfe56f1f61dded1/images
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODBlYjdlMjI3ZjcyNWJiYmMzZjVlOTkiLCJ1c2VybmFtZSI6InRlc3R1c2VyIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDU3OTUxNjQsImV4cCI6MTc0NTc5ODc2NH0._Xt4L997iMxFyIfREJPoP862t8SYClxiROwk1Je879Y
Content-Type: multipart/form-data

--boundary
Content-Disposition: form-data; name="images"; filename="test.jpg"
Content-Type: image/jpeg

@images/test.jpg
--boundary--